name: Test GitHub Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev/jasongin/action

jobs:
  no-basis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup debug session
      uses: mxschmitt/action-tmate@v3
      with:
        timeout-minutes: 15
        detached: false
